spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true  
#server:
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
 
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000

item-service:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ConnectTimeout: 1000
    ReadTimeout: 500
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
---
spring:
  profiles: order1
  
server:
  port: 8201     
---
spring:
  profiles: order2
server:
  port: 8202  


